### ISSUE TITLE
Thank you for developing this LSP server, it is the basis of new Castle Game Engine VS Code extension

### ISSUE THREAD

**Issue by michaliskambi** [Isopod/pascal-language-server#7]
( Sorry for abusing the GitHub issues for essentially just sending a message to you @Isopod -- I didn't find any other way to contact you, and I really wanted to express my gratitude. If needed, my email is `michalis@castle-engine.io` . I'll create + close this issue, as there's no action needed, this is all just FYI. )

As you may recall, we use a fork of your LSP for Pascal ( https://github.com/castle-engine/pascal-language-server ) in Castle Game Engine ( https://castle-engine.io/ ). We've just released something big: a dedicated VS Code extension for "Castle Game Engine", bundling Pascal LSP and operations on CGE projects. 

- All the details are in [news post](https://castle-engine.io/wp/2024/03/08/new-vs-code-extension-to-integrate-with-castle-game-engine-perfectly-build-run-debug-cge-projects-use-pascal-with-code-completion-and-highlighting/) .
- With more docs on https://castle-engine.io/vscode
- The extension is published in the VS Code marketplace, https://marketplace.visualstudio.com/items?itemName=castle-engine-team.castle-engine .
- Extension source code is in https://github.com/castle-engine/castle-engine-vscode

Some of the features will work only inside _Castle Game Engine_ project (directory with `CastleEngineManifest.xml` file), some for all Pascal files -- in particular code completion using LSP works in any Pascal project.

We've done underneath some improvements to the pasls -- we'll contribute back the general things, as before! Most of the really CGE-specific things (like understanding what is "Castle Game Engine project" and adding paths from CastleEngineManifest.xml) is in the [VS Code extension](https://github.com/castle-engine/castle-engine-vscode), not in [LSP](https://github.com/castle-engine/pascal-language-server), so I hope we'll be able to contribute most of our changes :)

Thank you for developing your LSP -- without it, our whole VS Code extension would not really have the "core" feature which is code completion for Pascal.

**Comment by Isopod** [comment]
Thanks for the update and for contributing back your changes! You can find my e-mail in the commit history, but this way is fine, too. I'll be happy to merge your changes when you're ready.
